### ISSUE TITLE
just not working for Java code

### ISSUE THREAD

**Issue by canoeberry** [spadgos/sublime-jsdocs#354]
If I have a perfectly formed comment:

        /**
         * Adds a new reference to the hash table.
         * @param ref the reference to add
         */

and run jsdoc_wrap_lines when the cursor is at the beginning of the last line with "*/" I end up with no changes but the cursor at the end of the line "to add".

But if I run the command again, I get this:

        /**
         * Adds a new reference to the hash table.
         * @param ref the reference to add
          * /

And if I go back to the original comment and put the cursor anywhere on the first line of text, I get this:

        /**
         * Adds a new reference to the hash table.
          *
          * @param ref the reference to add
         */

So it changes the indent of the "*" on subsequent lines for some reason. And then again, if I run the command on one of those indented "*" lines it does it some more:

        /**
         * Adds a new reference to the hash table.
          *
           *
           * @param ref the reference to add
         */

I have to assume this is not affecting other people otherwise they would agree that this is not usable. So - any idea what I am doing wrong?

I am running the latest Sublime 3 beta (not dev) on Mac OS X.

**Comment by spadgos** [comment]
> So - any idea what I am doing wrong?

Okay so it looks like it's a bug in how DocBlockr selects all the text of the comment. In the Java tmLanguage, it creates a new scope for the tags (`@param`), whereas it was written assuming that the entire comment block would be a single scope, so the plugin expands the selection to the scope. Depending on where your cursor is here, it'll select just the first line, just the word `@param`, or the description of the param, and then try to format that and that's why things go awry.

I've put together a fix which uses a very primitive way to expand to the selection properly. That should fix things for you.

**Comment by canoeberry** [comment]
Cheers. Seems to work better for me now.
