### ISSUE TITLE
Automatic return tag

### ISSUE THREAD

**Issue by alphanull** [spadgos/sublime-jsdocs#407]
Would be more convenient that when documenting a method, DocBlockr only adds `@return` if there is actually a `return` present in the following code block - or even better, if there is actually something following this return.

I.e. if I only have `return;`-> do not add this tag, if I have `return something;` -> add it.

**Comment by Tilogorn** [comment]
If you validate your code&docblocks against `PHP_CodeSniffer`, it will immediately show an error if `@return` is missing (`ERROR | Missing @return tag in function comment`).

In cases you do not have a return value, you can use `@return void` as written in the [PHPdoc docs](http://www.phpdoc.org/docs/latest/references/phpdoc/tags/return.html).

**Comment by spadgos** [comment]
@alphanull by design, docblockr doesn't try to do any intelligent parsing of the function body. It simply uses regex parsing the arguments list. Doing more than that adds exponential complication to parse and interpret all the different supported languages.

The solution is: just delete the line with `@return` when you don't actually want it.
